AOTrade/AOTrade/Controllers/CashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AOTrade.Models.Entity;
using AOTrade.Models.ViewModel;
using AOTrade.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AOTrade.Controllers
{
    public class CashController : Controller
    {
        private readonly ISettingsService _settingsService;
        private readonly IMapper _mapper;
        private readonly ICashService _cashService;

        public CashController(ISettingsService settingsService, IMapper mapper, ICashService cashService)
        {
            _settingsService = settingsService;
            _cashService = cashService;
            _mapper = mapper;
        }
        /////////////--------------------------  C R U D ---------------------------------////////////////

        #region Expense
        #region Get Method
        public IActionResult Expense()
        {
            return View();
        }
        [HttpGet]
        public IActionResult ExpenseForm(int id = 0)
        {
            try
            {
                var viewModel = new ExpenseVM()
                {
                    Date = DateTime.UtcNow.AddHours(6)
                };
                if (id > 0)
                {
                    viewModel = _cashService.GetExpense(id);
                    if (viewModel == null)
                    {
                        return Json(new { act = false, msg = "Data not found" });
                    }
                }
                ViewBag.ItemId = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_settingsService.GetItem()
                    .Where(m => m.GroupId == viewModel.ItemGroupId).ToList(), "Id", "ItemName");
                ViewBag.ItemGroupId = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_settingsService.GetItemGroup(), "Id", "GroupName", viewModel.ItemGroupId);
                return PartialView("ExpenseForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult ExpenseList(String from, String to)
        {
            try
            {
                var viewModel = _cashService.GetExpense();
                return PartialView("ExpenseList", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveExpense(ExpenseVM model)
        {
            if (!ModelState.IsValid) { return Json(new { act = false, msg = "Error! Invalid input" }); }
            try
            {
                model.CreateDate = DateTime.UtcNow.AddHours(6);
                await _cashService.SaveExpenseAsync(model);
                    var viewModel = _cashService.GetExpense();
                    return PartialView("ExpenseList", viewModel);
            }
            catch (Exception ex)
            {
                return Json(new { act = false, msg = "Error! Data not saved" });
            }
        }

        [HttpPost]
        public async Task<JsonResult> ExpenseDelete(int id)
        {
            try
            {
                await _cashService.DeleteExpenseAsync(id);
                return Json(new { act = true, msg = "Deleted! Changes saved successfully" });
            }
            catch (Exception ex)
            {
                //throw ex;
                return Json(new { act = false, msg = "Error! Error occured" });
            }
        }
        #endregion
        #endregion

        #region Income
        #region Get Method
        public IActionResult Income()
        {
            return View();
        }

        [HttpGet]
        public IActionResult IncomeForm(int id = 0)
        {
            try
            {
                var viewModel = new IncomeVM()
                {
                    Date = DateTime.UtcNow.AddHours(6)
                };
                if (id > 0)
                {
                    viewModel = _cashService.GetIncome(id);
                    if (viewModel == null)
                    {
                        return Json(new { act = false, msg = "Data not found" });
                    }
                }
                SetIncomeViewBag("Income", viewModel);
                return PartialView("IncomeForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult IncomeList(String from, String to)
        {
            try
            {
                var viewModel = _cashService.GetIncome();
                return PartialView("IncomeList", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveIncome(IncomeVM model)
        {
            if (!ModelState.IsValid) { return Json(new { act = false, msg = "Error! Invalid input" }); }
            try
            {
                model.CreateDate = DateTime.UtcNow.AddHours(6);
                await _cashService.SaveIncomeAsync(model);

                var viewModel = _cashService.GetIncome();
                return PartialView("IncomeList", viewModel);
            }
            catch (Exception ex)
            {
                return Json(new { act = false, msg = "Error! Data not saved" });
            }
        }

        [HttpPost]
        public async Task<JsonResult> IncomeDelete(int id)
        {
            try
            {
                await _cashService.DeleteIncomeAsync(id);
                return Json(new { act = true, msg = "Deleted! Changes saved successfully" });
            }
            catch (Exception ex)
            {
                //throw ex;
                return Json(new { act = false, msg = "Error! Error occured" });
            }
        }
        #endregion
        #endregion






        ////////////-----------------------------------------------/////////////////////

        #region Private method



        private void SetIncomeViewBag(string title, IncomeVM model)
        {
            //TODO: UT
            try
            {
                ViewBag.IsModelValid = true;
                ViewBag.Title = title;
                ViewBag.ItemGroupId = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_settingsService.GetItemGroup(), "Id", "GroupName", model.ItemGroupId);
                ViewBag.ItemId = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_settingsService.GetItem().Where(m => m.GroupId == model.ItemGroupId).ToList(), "Id", "ItemName");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion
    }
}

AOTrade/AOTrade/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AOTrade.Controllers
{
    public class ReportController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AOTrade/AOTrade/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AOTrade.Models.ViewModel;
using AOTrade.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AOTrade.Controllers
{
    public class StockController : Controller
    {
        private readonly ISettingsService _settingsService;
        private readonly ICashService _cashService;
        private readonly IMapper _mapper;

        public StockController(ISettingsService settingsService, IMapper mapper, ICashService cashService)
        {
            _settingsService = settingsService;
            _cashService = cashService;
            _mapper = mapper;
        }

        /////////////--------------------------  C R U D ---------------------------------////////////////


        #region Purchase
        #region Get Method
        public IActionResult Purchase()
        {
            return View();
        }
        [HttpGet]
        public IActionResult PurchaseForm(int id = 0)
        {
            try
            {
                var viewModel = new ExpenseVM()
                {
                    Date = DateTime.UtcNow.AddHours(6)
                };
                if (id > 0)
                {
                    viewModel = _cashService.GetExpense(id);
                    if (viewModel == null)
                    {
                        return Json(new { act = false, msg = "Data not found" });
                    }
                }
                ViewBag.CompanyId = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_settingsService.GetCompany(), "Id", "CompanyName");
                return PartialView("PurchaseForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult PurchaseList(String from, String to)
        {
            try
            {
                var viewModel = _cashService.GetExpense();
                return PartialView("ExpenseList", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SavePurchase(ExpenseVM model)
        {
            if (!ModelState.IsValid) { return Json(new { act = false, msg = "Error! Invalid input" }); }
            try
            {
                model.CreateDate = DateTime.UtcNow.AddHours(6);
                await _cashService.SaveExpenseAsync(model);
                var viewModel = _cashService.GetExpense();
                return PartialView("ExpenseList", viewModel);
            }
            catch (Exception ex)
            {
                return Json(new { act = false, msg = "Error! Data not saved" });
            }
        }

        [HttpPost]
        public async Task<JsonResult> PurchaseDelete(int id)
        {
            try
            {
                await _cashService.DeleteExpenseAsync(id);
                return Json(new { act = true, msg = "Deleted! Changes saved successfully" });
            }
            catch (Exception ex)
            {
                //throw ex;
                return Json(new { act = false, msg = "Error! Error occured" });
            }
        }
        #endregion
        #endregion

        #region Sale
        #region Get Method
        public IActionResult Sale()
        {
            return View();
        }
        [HttpGet]
        public IActionResult SaleForm(int id = 0)
        {
            try
            {
                var viewModel = new ExpenseVM()
                {
                    Date = DateTime.UtcNow.AddHours(6)
                };
                if (id > 0)
                {
                    viewModel = _cashService.GetExpense(id);
                    if (viewModel == null)
                    {
                        return Json(new { act = false, msg = "Data not found" });
                    }
                }
                ViewBag.CompanyId = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_settingsService.GetCompany(), "Id", "CompanyName");
                return PartialView("SaleForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult SaleList(String from, String to)
        {
            try
            {
                var viewModel = _cashService.GetExpense();
                return PartialView("SaleList", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveSale(ExpenseVM model)
        {
            if (!ModelState.IsValid) { return Json(new { act = false, msg = "Error! Invalid input" }); }
            try
            {
                model.CreateDate = DateTime.UtcNow.AddHours(6);
                await _cashService.SaveExpenseAsync(model);
                var viewModel = _cashService.GetExpense();
                return PartialView("ExpenseList", viewModel);
            }
            catch (Exception ex)
            {
                return Json(new { act = false, msg = "Error! Data not saved" });
            }
        }

        [HttpPost]
        public async Task<JsonResult> SaleDelete(int id)
        {
            try
            {
                await _cashService.DeleteExpenseAsync(id);
                return Json(new { act = true, msg = "Deleted! Changes saved successfully" });
            }
            catch (Exception ex)
            {
                //throw ex;
                return Json(new { act = false, msg = "Error! Error occured" });
            }
        }
        #endregion
        #endregion
    }
}

AOTrade/AOTrade/Views/Shared/InnerReportHeader.cshtml
<div class="row" style="margin: 0 0 20px 0px; border-bottom:2px solid #113671; padding-bottom:10px">
    <div style="width:12%; float:left">
        <img src="~/images/logo.png" class="img-responsive img-circle" style="height:60px;position:relative; left:15px;">
    </div>
    <div style="width:88%;  float:left; font-size:22px; color: #074874;position:relative; top:20px; font-weight:400">Abu Omar Trading Corporation</div>
</div>

AOTrade/AOTrade/Views/Shared/_InitialLayout .cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @*AOTrade*@</title>
    <!-- App css -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
</head>

<body>

    <!-- Begin page -->
    <div id="wrapper">

                @RenderBody()

        <!-- ============================================================== -->
        <!-- Main content END here -->
        <!-- ============================================================== -->


    </div>
    <!-- END wrapper -->
    <!-- jQuery  -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <!-- Toastr js -->
    <script src="~/lib/jquery-toastr/jquery.toast.min.js" type="text/javascript"></script>
    <script src="~/js/pages/jquery.toastr.js" type="text/javascript"></script>
</body>
</html>

AOTrade/AOTrade/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AOTrade</title>

    @*<environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>*@


    <!-- Plugins css Select 2-->
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" type="text/css" />

    <!-- Plugins css  Date Picker-->
    <link href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">


    <!-- Plugins css DataTables -->
    <link href="~/lib/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />


    <!-- Plugins css Toastr css -->
    <link href="~/lib/jquery-toastr/jquery.toast.min.css" rel="stylesheet" />


    <!-- Plugins css Sweet Alert-->
    <link href="~/lib/sweet-alert/sweetalert2.min.css" rel="stylesheet" type="text/css" />

    <!-- Plugins css File upload (image)-->
    @*<link href="~/lib/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" type="text/css" />*@

    <!-- App css -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/css/metismenu.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />


</head>

<body>

    <!-- Begin page -->
    <div id="wrapper">

        <!-- ========== Left Sidebar Start ========== -->
        @Html.Partial("_SideNav")
        <!-- Left Sidebar End -->

        <div class="content-page">
            <!-- Top Bar Start -->
            @Html.Partial("_TopNav")
            <!-- Top Bar End -->
            <!-- Start Page content -->
            <div class="content">

                @RenderBody()

            </div>

            <footer class="footer text-right">
                2019 © Abu Omar Trading Corporation
            </footer>

        </div>


        <!-- ============================================================== -->
        <!-- Main content END here -->
        <!-- ============================================================== -->


    </div>
    <!-- END wrapper -->
    <!-- jQuery  -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/metisMenu.min.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/jquery.slimscroll.js"></script>


    <!-- Select 2 -->
    <script src="~/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <!-- Init Js file "Related with select 2" -->
    <script type="text/javascript" src="~/js/pages/jquery.form-advanced.init.js"></script>


    <!-- Auto Numberic  -->
    <script src="~/lib/autoNumeric/autoNumeric.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(function ($) {
            $('.autonumber').autoNumeric('init');
        });
        jQuery.browser = {};
        (function () {
            jQuery.browser.msie = false;
            jQuery.browser.version = 0;
            if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
                jQuery.browser.msie = true;
                jQuery.browser.version = RegExp.$1;
            }
        })();
    </script>


    <!-- Date Picker  -->
    <script src="~/lib/bootstrap-timepicker/bootstrap-timepicker.js"></script>
    <script src="~/lib/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
    <script src="~/lib/clockpicker/js/bootstrap-clockpicker.min.js"></script>
    <script src="~/lib/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <!-- Init js "Related with Date Picker "-->
    <script src="~/js/pages/jquery.form-pickers.init.js"></script>


    <!-- Parsley js "For form validation"-->
    <script type="text/javascript" src="~/lib/parsleyjs/parsley.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('form').parsley();
        });
    </script>


    <!-- Datatable js -->
    <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            // Default Datatable
            $('#datatable').DataTable();

            // Responsive Datatable
            $('#responsive-datatable').DataTable();
        });
    </script>


    <!-- Toastr js -->
    <script src="~/lib/jquery-toastr/jquery.toast.min.js" type="text/javascript"></script>
    <script src="~/js/pages/jquery.toastr.js" type="text/javascript"></script>


    <!-- Sweet Alert Js  -->
    <script src="~/lib/sweet-alert/sweetalert2.min.js"></script>
    <script src="~/js/pages/jquery.sweet-alert.init.js"></script>

    <!-- Sweet Alert Js  -->
    <script src="~/lib/bootstrap-fileupload/bootstrap-fileupload.js"></script>

    <!--   -->
    <!-- App js -->
    <script src="~/js/jquery.core.js"></script>
    <script src="~/js/jquery.app.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/formdynamic.js"></script>





    @*<environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>*@

    @RenderSection("Scripts", required: false)
</body>
</html>

AOTrade/AOTrade/Views/Shared/_SideNav.cshtml
<div class="left side-menu">

    <div class="slimscroll-menu" id="remove-scroll">

        <!-- User box -->
        <div class="user-box">
            <br />
            @*<span class="font-17 text-input-head">Balance: </span><span class="font-17 text-input-head">2,805,97,8.00</span>*@
            <br />
        </div>

        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul class="metismenu" id="">

                @*<ul class="metismenu" id="side-menu">*@
                <!-- id  "side-menu"  used to auto collapse side nav-->


                <!--<li class="menu-title">Navigation</li>-->
                @*<li>
            <a href="@Url.Action("Index", "Report")">
                <i class="fi-air-play"></i><span class="badge badge-danger badge-pill pull-right">7</span> <span> Report </span>
            </a>
        </li>*@

                <li>
                    <a href="javascript: void(0);"><i class="fa fa-circle-o"></i> <span> Cash </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level" aria-expanded="false">
                        <li><a href="@Url.Action("Expense", "Cash")">Expense</a></li>
                        <li><a href="@Url.Action("Income", "Cash")">Income</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);"><i class="fa fa-circle-o"></i> <span> Stock </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level" aria-expanded="false">
                        <li><a href="@Url.Action("Sale", "Stock")">Sale</a></li>
                        <li><a href="@Url.Action("Purchase", "Stock")">Purchase</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);"><i class="fa fa-circle-o"></i> <span> Payroll </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level" aria-expanded="false">
                        <li><a href="@Url.Action("Employee", "Payroll")">Employee</a></li>
                        <li><a href="@Url.Action("EmpSalary", "Payroll")">Salary</a></li>
                        <li><a href="@Url.Action("Bonus", "Payroll")">Bonus</a></li>
                        <li><a href="@Url.Action("EmpLoan", "Payroll")">Loan</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);"><i class="fa fa-gears"></i> <span> Settings </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level" aria-expanded="false">
                        <li><a href="@Url.Action("ItemGroup", "Settings")">Item group</a></li>
                        <li><a href="@Url.Action("Item", "Settings")">Item</a></li>
                        <li><a href="@Url.Action("Company", "Settings")">Company</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);"><i class="fa fa-circle-o"></i> <span> Lp Gas </span> <span class="menu-arrow"></span></a>
                    <ul class="nav-second-level" aria-expanded="false">
                        @*<li><a href="@Url.Action("Action", "Controller")">Expense</a></li>*@
                    </ul>
                </li>


            </ul>

        </div>
        <!-- Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>

AOTrade/AOTrade/Views/Shared/_TopNav.cshtml
<div class="topbar">

    <nav class="navbar-custom">

        <ul class="list-unstyled topbar-right-menu float-right mb-0">

            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <i class="fi-bell noti-icon"></i>
                    <span class="badge badge-danger badge-pill noti-icon-badge">4</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated dropdown-lg">

                    @*<!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5 class="m-0"><span class="float-right"><a href="" class="text-dark"><small>Clear All</small></a> </span>Notification</h5>
                    </div>

                    <div class="slimscroll" style="max-height: 230px;">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-success"><i class="mdi mdi-comment-account-outline"></i></div>
                            <p class="notify-details">Caleb Flakelar commented on Admin<small class="text-muted">1 min ago</small></p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info"><i class="mdi mdi-account-plus"></i></div>
                            <p class="notify-details">New user registered.<small class="text-muted">5 hours ago</small></p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-danger"><i class="mdi mdi-heart"></i></div>
                            <p class="notify-details">Carlos Crouch liked <b>Admin</b><small class="text-muted">3 days ago</small></p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-warning"><i class="mdi mdi-comment-account-outline"></i></div>
                            <p class="notify-details">Caleb Flakelar commented on Admin<small class="text-muted">4 days ago</small></p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-purple"><i class="mdi mdi-account-plus"></i></div>
                            <p class="notify-details">New user registered.<small class="text-muted">7 days ago</small></p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-custom"><i class="mdi mdi-heart"></i></div>
                            <p class="notify-details">Carlos Crouch liked <b>Admin</b><small class="text-muted">13 days ago</small></p>
                        </a>
                    </div>

                    <!-- All-->
                    <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                        View all <i class="fi-arrow-right"></i>
                    </a>*@

                </div>
            </li>

            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle nav-user" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <img src="~/images/noEmployee.png" alt="user" class="rounded-circle"> <span class="ml-1">Abcde defghij <i class="mdi mdi-chevron-down"></i> </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated dropdown-lg">

                    <!-- item-->
                    <div class="dropdown-item noti-title">
                    </div>

                    <div class="" style="max-height: 230px;">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item" style="font-size:15px">
                            Logout
                        </a>


                    </div>

                </div>
            </li>

        </ul>

        <ul class="list-inline menu-left mb-0">
            <li class="float-left">
                <button class="button-menu-mobile open-left">
                    <i class="dripicons-menu"></i>
                </button>
            </li>
        </ul>

    </nav>
</div>