AOTrade/AOTrade/Models/Entity/EmpBonus.cs
using System;
using System.Collections.Generic;

namespace AOTrade.Models.Entity
{
    public partial class EmpBonus
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public decimal Salary { get; set; }
        public int BonusPercent { get; set; }
        public decimal BonusAmmount { get; set; }
        public string Remarks { get; set; }
        public DateTime Date { get; set; }
        public int? CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? ApproveDate { get; set; }

        public Employee Emp { get; set; }
    }
}

AOTrade/AOTrade/Models/Entity/EmpLoan.cs
using System;
using System.Collections.Generic;

namespace AOTrade.Models.Entity
{
    public partial class EmpLoan
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public decimal LoanAmmount { get; set; }
        public decimal MonthlyDeduct { get; set; }
        public DateTime DeductDate { get; set; }
        public decimal DueAmmount { get; set; }
        public DateTime? Date { get; set; }
        public string Remarks { get; set; }
        public int? CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? ApproveDate { get; set; }

        public Employee Emp { get; set; }
    }
}

AOTrade/AOTrade/Models/Entity/EmpSalary.cs
using System;
using System.Collections.Generic;

namespace AOTrade.Models.Entity
{
    public partial class EmpSalary
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public int? SalaryMonth { get; set; }
        public int? SalaryYear { get; set; }
        public decimal LoanDueAmmount { get; set; }
        public decimal LoanDeduct { get; set; }
        public int AbsentDay { get; set; }
        public decimal AbsentDeduct { get; set; }
        public decimal Deduction { get; set; }
        public decimal GrossSalary { get; set; }
        public DateTime Date { get; set; }
        public int? CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? ApproveDate { get; set; }

        public Employee Emp { get; set; }
    }
}

AOTrade/AOTrade/Models/Entity/Employee.cs
using System;
using System.Collections.Generic;

namespace AOTrade.Models.Entity
{
    public partial class Employee
    {
        public Employee()
        {
            EmpBonus = new HashSet<EmpBonus>();
            EmpIncrement = new HashSet<EmpIncrement>();
            EmpLoan = new HashSet<EmpLoan>();
            EmpSalary = new HashSet<EmpSalary>();
        }

        public int Id { get; set; }
        public string EmpName { get; set; }
        public string EmpNameId { get; set; }
        public string Photo { get; set; }
        public string Designation { get; set; }
        public DateTime? JoinDate { get; set; }
        public string NidNo { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public DateTime? BirthDate { get; set; }
        public string BloodGroup { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public bool? IsEmployeeActive { get; set; }
        public decimal Salary { get; set; }
        public decimal BeginSalary { get; set; }
        public int? LoanId { get; set; }
        public decimal LoanAmmount { get; set; }
        public int? CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }

        public ICollection<EmpBonus> EmpBonus { get; set; }
        public ICollection<EmpIncrement> EmpIncrement { get; set; }
        public ICollection<EmpLoan> EmpLoan { get; set; }
        public ICollection<EmpSalary> EmpSalary { get; set; }
    }
}

AOTrade/AOTrade/Controllers/PayrollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AOTrade.Models.ViewModel;
using AOTrade.Services;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AOTrade.Controllers
{
    public class PayrollController : Controller
    {
        private readonly ISettingsService _settingsService;
        private readonly IMapper _mapper;
        private readonly ICashService _cashService;
        private readonly IPayrollService _payrollService;
        private readonly IHostingEnvironment _hostingEnvironment;
        //private readonly IHttpContextAccessor _contextAccessor;


        public PayrollController(ISettingsService settingsService, IMapper mapper, ICashService cashService, IPayrollService payrollService, IHostingEnvironment hostingEnvironment)
        {
            _settingsService = settingsService;
            _cashService = cashService;
            _payrollService = payrollService;
            _hostingEnvironment = hostingEnvironment;
            //_contextAccessor = contextAccessor;
            _mapper = mapper;
        }
        /////////////--------------------------  C R U D ---------------------------------////////////////


        #region Employee
        #region Get Method
        public IActionResult Employee()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EmployeeForm(int id = 0)
        {
            try
            {
                var viewModel = new EmployeeVM();
                if (id > 0)
                {
                    viewModel = _payrollService.GetEmployee(id);
                    if (viewModel == null)
                    {
                        return Json(new { act = false, msg = "Data not found" });
                    }
                }
                return PartialView("EmployeeForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult EmployeeList(int eId)
        {
            try
            {
                var viewModel = _payrollService.GetEmployee();
                return PartialView("EmployeeList", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveEmployee(EmployeeVM model, IFormFile photoFile)
        {
            if (!ModelState.IsValid) { return Json(new { act = false, msg = "Error! Invalid input" }); }
            try
            {
                model.EmpNameId = model.Id +", "+ model.EmpName;

                int nid = model.Id;
                if (model.Id == 0){
                    model.BeginSalary = (decimal)model.Salary;

                    var yr = Convert.ToDateTime(DateTime.UtcNow.AddHours(6)).Year.ToString();
                    int year = Int32.Parse(yr.Substring(yr.Length - 2));
                    var t = _payrollService.GetEmployee().Max(u => (int?)u.Id).ToString();
                    if (t == null || t == ""){t = "0000";}
                    int ids = Int32.Parse(t.Substring(t.Length - 3)) + 1;
                    nid = year * 1000 + ids;
                    model.empNewId = nid;
                }

                var hostPath = _hostingEnvironment.WebRootPath;
                var dataPath = "/images/";
                var savepath = hostPath + dataPath;
                int height =450;
                int width = 350;
                var ext = ".png";
                _payrollService.Comm_ImageFormatForStoreWithNameAndExt(nid.ToString(), photoFile, savepath, height, width, ext);

                model.Photo = dataPath + model.Id.ToString() + ext;
                model.CreateDate = DateTime.UtcNow.AddHours(6);

                await _payrollService.SaveEmployeeAsync(model);

                var viewModel = _payrollService.GetEmployee();
                return PartialView("EmployeeList", viewModel);
            }
            catch (Exception ex)
            {
                return Json(new { act = false, msg = "Error! Data not saved" });
            }
        }

        [HttpPost]
        public async Task<JsonResult> EmployeeDelete(int id)
        {
            try
            {
                await _payrollService.DeleteEmployeeAsync(id);
                return Json(new { act = true, msg = "Deleted! Changes saved successfully" });
            }
            catch (Exception ex)
            {
                //throw ex;
                return Json(new { act = false, msg = "Error! Error occured" });
            }
        }
        #endregion
        #endregion

        /////---------------------//  BONUS   //-----------------------------///////////

        #region Bonus
        #region Get Method
        public IActionResult Bonus()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EmpBonusForm(int id = 0)
        {
            try
            {
                var viewModel = new BonusRecordVM();

                //List<EmployeeVM> EmpList = _payrollService.GetEmployee();

                //viewModel.EmployeeVMList = EmpList;

                //if (id > 0)
                //{
                //    if (viewModel == null)
                //    {
                //        return Json(new { act = false, msg = "Data not found" });
                //    }
                //}
                return PartialView("EmpBonusForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        //[HttpGet]
        //public IActionResult EmployeeList(String from, String to)
        //{
        //    try
        //    {
        //        var viewModel = _payrollService.GetEmployee();
        //        return PartialView("EmployeeList", viewModel);
        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }
        //}
        #endregion

        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEmpBonus(BonusRecordVM model)
        {
            if (!ModelState.IsValid) { return Json(new { act = false, msg = "Error! Invalid input" }); }
            try
            {
                var viewModel = model;

                viewModel.EmployeeVMList = _payrollService.GetEmployee();

                decimal pers = 0;
                if (model.BonusPercent != null)
                {
                    pers = (decimal)model.BonusPercent;
                }
                

                foreach (var item in viewModel.EmployeeVMList)
                {
                    // Here begin salary used as Bonus Amount :D 

                    item.BeginSalary = (decimal)(item.Salary * (pers / 100));
                }


                return PartialView("EmpBonusList", viewModel);
            }
            catch (Exception ex)
            {
                return Json(new { act = false, msg = "Error! Data not saved" });
            }
        }

        //[HttpPost]
        //public async Task<JsonResult> EmpBonusDelete(int id)
        //{
        //    try
        //    {
        //        await _payrollService.DeleteEmployeeAsync(id);
        //        return Json(new { act = true, msg = "Deleted! Changes saved successfully" });
        //    }
        //    catch (Exception ex)
        //    {
        //        //throw ex;
        //        return Json(new { act = false, msg = "Error! Error occured" });
        //    }
        //}
        #endregion
        #endregion

        /////---------------------//  Employee Salary   //-----------------------------///////////

        #region Employee Salary
        #region Get Method
        public IActionResult EmpSalary()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EmpSalaryForm(int id = 0)
        {
            try
            {
                var viewModel = new EmpSalaryVM {
                    Date = DateTime.UtcNow.AddHours(6)
                };
                viewModel.EmployeeVMList = _payrollService.GetEmployee();
                if (id > 0)
                {
                    viewModel = _payrollService.GetEmpSalary(id);
                    if (viewModel == null)
                    {
                        return Json(new { act = false, msg = "Data not found" });
                    }
                    viewModel.EmployeeVMList = _payrollService.GetEmployee().Where(m => m.Id == viewModel.EmpId).ToList();
                    viewModel.EmpSalaryVMList = _payrollService.GetEmpSalary().Where(m => m.Id == id).ToList();
                    viewModel.EmpSalaryVMList[0].EmpId = viewModel.EmpId;
                    viewModel.EmpSalaryVMList[0].AbsentDay = viewModel.AbsentDay;
                }
                return PartialView("EmpSalaryForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult EmpSalaryList(int eId)
        {
            try
            {
                var viewModel = _payrollService.GetEmpSalary();
                return PartialView("EmpSalaryList", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveEmpSalary(EmpSalaryVM model)
        {
            //if (!ModelState.IsValid) { return Json(new { act = false, msg = "Error! Invalid input" }); }
            
            try
            {
                foreach (var item in model.EmpSalaryVMList)
                {

AOTrade/AOTrade/Views/Payroll/Bonus.cshtml
@{
    ViewData["Title"] = "ItemGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


        <div class="card-box" id="genericView">
            <input type="hidden" value="EmpBonusForm" id="formUrl">
            <input type="hidden" value="/Payroll/EmpBonusDelete/" id="deleteUrl">

                <div class="form-sec">
                    <form asp-controller="Payroll" asp-action="SaveEmpBonus" id="reportsData">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div id="formUI"></div>
                    </form>
                </div>


            <div class="table-responsive">
                @*<input type="hidden" value="EmpBonusList" id="datatableUrl">*@
                <div class="" id="reportsList">
                    @*------------------Table Data------------------*@
                </div>
            </div>
        </div>

AOTrade/AOTrade/Views/Payroll/EmpBonusForm.cshtml
@model AOTrade.Models.ViewModel.BonusRecordVM
<input asp-for="Id" type="hidden" />

<div class="row">
    <div class="col-sm-12">
        <h4 class="m-t-0 m-b-30">Employee Bonus</h4>
    </div>
</div>

<div class="row" style="padding: 0 10px 0 10px">
    <div class="col-sm-1"></div>
        <div class="col-sm-2">
            <span class="font-14 text-input-head">Bonus title</span>
            <input asp-for="Title" class="form-control" required />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="col-sm-3">
            <span class="font-14 text-input-head">Description</span>
            <input asp-for="Description" class="form-control" placeholder="" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="col-sm-2">
            <span class="font-14 text-input-head">Percent</span>
            <input asp-for="BonusPercent" class="form-control autonumber" placeholder="10%" required />
            <span asp-validation-for="BonusPercent" class="text-danger"></span>
        </div>
        <div class="col-sm-2">
            <span class="font-14 text-input-head">Date</span>
            <input asp-for="Date" type="text" class="form-control datepicker-autoclose" placeholder="mm/dd/yyyy" required />
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>
        <div class="col-sm-2">
            <span class="font-14 text-white">.</span>
            <input class="btn btn-success ." value="Submit" type="submit" style="width:100%;" />
        </div>
    </div>





    <script src="~/js/pages/jquery.form-pickers.init.js"></script>

AOTrade/AOTrade/Views/Payroll/EmpBonusList.cshtml
@model AOTrade.Models.ViewModel.BonusRecordVM

<page size="A4">
    <br />
    <div class="row" style="border-bottom:1px solid #0f7b80; margin:10px">
        <div class="col-sm-8"></div>
        <div class="col-sm-4">
            <a onclick="tablesToExcel(array1, array2, 'myfile.xls')" class="btn btn-outline-secondary"><i class="fa fa-download"></i>&nbsp; xls</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a id="printarea" class="btn btn-outline-secondary"><i class="fa fa-download"></i>&nbsp; pdf</a>
        </div>
        <br /><br /><br />
    </div>
    <br />

    <div id="printTable">

        @*---------------------------------Design Report from here------------------------*@
        <link href="~/css/report.css" rel="stylesheet" type="text/css" />
        <div style="padding: 5px">
            @*-----report header------*@
            @await Html.PartialAsync("~/Views/Shared/InnerReportHeader.cshtml")
            @*----------------------------*@


            <table class="table table-borderless" id="1">
                <tr>
                    <td style="padding:0 0 10px 0">
                        <div style="width:100%; color:#2b313b; float:left">
                            <div style="float:left">
                                <div style="padding-bottom:5px;font-size:16px;">@Html.DisplayFor(model => model.Title) &nbsp; Bonus </div>
                                <div style=" max-width: 500px; word-break: break-all; padding-bottom:10px; font-size:13px;">
                                    @Html.DisplayFor(model => model.Description)
                                </div>
                            </div>

                            <div style="font-size:14px; width:40%; float:right">
                                <table align="right" class="table" style="width:70%; border:0px">
                                    <tr style="border:0px">
                                        <td width="40%" align="left" style="padding:0px">Date: @Html.DisplayFor(model => model.Date)</td>
                                    </tr>
                                    <tr style="border:0px">
                                        <td width="40%" align="left" style="padding:0px">Total amount: 2000000.00 &nbsp;</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>


            <table class="table table-bordered" style="width:100%;margin:-30px -20px 0 0" id="2">
                <tr style="text-align:left">
                    <th>
                        ID
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Designation
                    </th>
                    <th>
                        Salary
                    </th>
                    <th>
                        Percent
                    </th>
                    <th>
                        Bonus Amount
                    </th>
                    <th>
                        Signature
                    </th>
                </tr>

                @foreach (var item in Model.EmployeeVMList)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EmpName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Designation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Salary)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => modelItem.BonusPercent)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BeginSalary)
                        </td>
                        <td></td>
                    </tr>
                }
            </table>

        </div>

    </div>

</page>



<script src="~/js/printreport.js"></script>

AOTrade/AOTrade/Views/Payroll/EmpLoan.cshtml
@{
    ViewData["Title"] = "ItemGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model AOTrade.Models.ViewModel.EmpLoanVM

<div class="card-box" id="genericView">
    <input type="hidden" value="EmpLoanForm" id="formUrl">
    <input type="hidden" value="/Payroll/EmpLoanDelete/" id="deleteUrl">

    <div class="form-sec">
        <form asp-controller="Payroll" asp-action="SaveEmpLoan" id="xformdata">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="formUI">

            </div>
        </form>
    </div>


    <input type="hidden" value="EmpLoanList" id="datatableUrl">
    <div class="tbl-sec table-responsive" id="xdataList">
        @*------------------Table Data------------------*@
    </div>
</div>

AOTrade/AOTrade/Views/Payroll/EmpLoanForm.cshtml
@model AOTrade.Models.ViewModel.EmpLoanVM
<input asp-for="Id" type="hidden" />

<div class="row">
    <div class="col-sm-10">
        <h4 class="m-t-0 m-b-30">Employee Loan</h4>
    </div>
    <div class="col-sm-2">
        <span class="font-14 text-input-head">Date</span>
        <input asp-for="Date" type="text" id="dated" class="form-control datepicker-autoclose" placeholder="mm/dd/yyyy" required />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>
</div>

<div class="row">
    <div class="col-sm-3">
        <span class="font-14 text-input-head">Employee name</span>
        <select asp-for="EmpId" asp-items="ViewBag.EmpId" class="form-control select2" required>
            <option value="">--  Select Employee  --</option>
        </select>
        <span asp-validation-for="EmpId" class="text-danger"></span>
    </div>

    <div class="col-sm-2">
        <span class="font-14 text-input-head">Loan amount</span>
        <input asp-for="LoanAmmount" class="form-control autonumber" required />
        <span asp-validation-for="LoanAmmount" class="text-danger"></span>
    </div>

    <div class="col-sm-2">
        <span class="font-14 text-input-head">Monthly deduction</span>
        <input asp-for="MonthlyDeduct" class="form-control autonumber" required />
        <span asp-validation-for="MonthlyDeduct" class="text-danger"></span>
    </div>

    <div class="col-sm-2">
        <span class="font-14 text-input-head">Deduction date</span>
        <input asp-for="DeductDate" type="text" class="form-control datepicker-autoclose" placeholder="mm/dd/yyyy" required />
        <span asp-validation-for="DeductDate" class="text-danger"></span>
    </div>

    <div class="col-sm-2">
        <span class="font-14 text-input-head">Remarks</span>
        <input asp-for="Remarks" class="form-control" />
        <span asp-validation-for="Remarks" class="text-danger"></span>
    </div>
    <div class="col-sm-1">
        <span class="font-14 text-transparent">Save</span>
        <input class="btn btn-success save" value="Save" type="submit" style="width:100%" />
    </div>
</div>

<script src="~/js/pages/jquery.form-pickers.init.js"></script>

AOTrade/AOTrade/Views/Payroll/EmpLoanList.cshtml
@model IEnumerable<AOTrade.Models.ViewModel.EmpLoanVM>

<table class="table table-bordered data-table">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th>
                Loan
            </th>
            <th>
                Monthly deduct
            </th>
            <th>
                Deduct date
            </th>
            <th>
                Due loan
            </th>
            <th>
                Date
            </th>
            <th>
               Remarks
            </th>
            <th style="width: 75px;
    text-align: center;"></th>
        </tr>
    </thead>
    <tbody>
        @{int sl = 0; }
        @foreach (var item in Model)
        {
            sl++;
        <tr>
            <td>
                @sl
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Emp.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Emp.EmpName) (@Html.DisplayFor(modelItem => item.Emp.Designation))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoanAmmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MonthlyDeduct)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeductDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueAmmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Remarks)
            </td>
            <td class="edit-delete" style="width: 75px;
    text-align: center;">
                <a title="Edit" class="fa fa-edit fa-lg add-update" href="#" id="@item.Id"></a>&nbsp;
                @Html.Raw(" | ")&nbsp;<a title="Delete" class="text-danger fa fa-lg fa-trash-o delete" href="#" id="@item.Id"></a>
            </td>
        </tr>
        }
    </tbody>
</table>

AOTrade/AOTrade/Views/Payroll/EmpSalary.cshtml
@{
    ViewData["Title"] = "ItemGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

        <div class="card-box" id="genericView">

            <input type="hidden" value="EmpSalaryForm" id="formUrl">
            <input type="hidden" value="/Payroll/EmpSalaryDelete/" id="deleteUrl">

                <div class="form-sec">
                    <form asp-controller="Payroll" asp-action="SaveEmpSalary" id="xformdata">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div id="formUI">

                        </div>
                    </form>
                </div>


                <input type="hidden" value="EmpSalaryList" id="datatableUrl">
                <div class="tbl-sec table-responsive" id="xdataList">
                    @*------------------Table Data------------------*@
                </div>
        </div>

AOTrade/AOTrade/Views/Payroll/EmpSalaryForm.cshtml
@model AOTrade.Models.ViewModel.EmpSalaryVM
<input asp-for="Id" type="hidden" />
<div class="row">
    <div class="col-sm-10">
        <h4 class="m-t-0 m-b-30">Employee Salary</h4>
    </div>
    <div class="col-sm-2">
        <span class="font-14 text-input-head">Date</span>
        <input asp-for="Date" type="text" class="form-control datepicker-autoclose" placeholder="mm/dd/yyyy" required />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>
</div> <br />
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th width="7%">
                        #
                    </th>
                    <th width="13%">
                        Employee ID
                    </th>
                    <th width="37%">
                        Name
                    </th>
                    <th width="23%">
                        Designation
                    </th>
                    <th width="20%">
                        Absent day/days
                    </th>
                </tr>
            </thead>
            <tbody>
                @{int indx = 0; int sl = 0; }
                @foreach (var item in Model.EmployeeVMList)
                {
                    sl++;
                    <tr>
                        <td>
                            @sl
                        </td>
                        <td>
                            <label class="text-form-label">@item.Id</label>
                            <input asp-for="EmpSalaryVMList[indx].EmpId" class="form-control" value="@item.Id" required type="hidden" />
                            <span asp-validation-for="EmpSalaryVMList[indx].EmpId" class="text-danger"></span>
                        </td>
                        <td>
                            <label class="text-form-label">@item.EmpName</label>
                        </td>
                        <td>
                            <label class="text-form-label">@item.Designation</label>
                        </td>
                        <td style="padding:0">
                            <input asp-for="EmpSalaryVMList[indx].AbsentDay" min=0 oninput="validity.valid||(value='');" class="form-control" style="font-size:16px;text-align:center" required />
                            <span asp-validation-for="EmpSalaryVMList[indx].EmpId" class="text-danger"></span>
                        </td>
                    </tr>


                    indx++;
                }
            </tbody>
        </table>
    </div>

</div>

<div class="row">
    <div class="col-sm-10"></div>
    <div class="col-sm-2">
        <span class="font-14 text-transparent">.</span>
        <input class="btn btn-success" value="Submit" type="submit" style="width:100%;" />
    </div>
</div>

<script src="~/js/pages/jquery.form-pickers.init.js"></script>

AOTrade/AOTrade/Views/Payroll/Employee.cshtml
@{
    ViewData["Title"] = "ItemGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

        <div class="card-box" id="genericView">
            <input type="hidden" value="EmployeeForm" id="formUrl">
            <input type="hidden" value="/Payroll/EmployeeDelete/" id="deleteUrl">


                <div class="form-sec">
                    <form asp-controller="Payroll" asp-action="SaveEmployee" id="xformdata">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div id="formUI">

                        </div>
                    </form>
                </div>


                <input type="hidden" value="EmployeeList" id="datatableUrl">
                <div class="tbl-sec table-responsive" id="xdataList">
                    @*------------------Table Data------------------*@
                </div>
        </div>