AOTrade/AOTrade/Models/Entity/Company.cs
using System;
using System.Collections.Generic;

namespace AOTrade.Models.Entity
{
    public partial class Company
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Description { get; set; }
        public decimal CompanyPercent { get; set; }
        public decimal? CurrentAmmount { get; set; }
        public decimal? CurrentStockAmmount { get; set; }
        public int? CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}

AOTrade/AOTrade/Models/Entity/Item.cs
using System;
using System.Collections.Generic;

namespace AOTrade.Models.Entity
{
    public partial class Item
    {
        public Item()
        {
            Expense = new HashSet<Expense>();
            Income = new HashSet<Income>();
        }

        public int Id { get; set; }
        public int GroupId { get; set; }
        public string ItemName { get; set; }
        public int? OuterTableId { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public int? CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }

        public ItemGroup Group { get; set; }
        public ICollection<Expense> Expense { get; set; }
        public ICollection<Income> Income { get; set; }
    }
}

AOTrade/AOTrade/Models/Entity/ItemGroup.cs
using System;
using System.Collections.Generic;

namespace AOTrade.Models.Entity
{
    public partial class ItemGroup
    {
        public ItemGroup()
        {
            Expense = new HashSet<Expense>();
            Income = new HashSet<Income>();
            Item = new HashSet<Item>();
        }

        public int Id { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public bool Editable { get; set; }
        public string Type { get; set; }
        public int? CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }

        public ICollection<Expense> Expense { get; set; }
        public ICollection<Income> Income { get; set; }
        public ICollection<Item> Item { get; set; }
    }
}

AOTrade/AOTrade/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AOTrade.Models.Entity;
using AOTrade.Models.ViewModel;
using AOTrade.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AOTrade.Controllers
{
    public class SettingsController : Controller
    {

        private readonly ISettingsService _settingsService;
        private readonly IMapper _mapper;

        public SettingsController(ISettingsService settingsService, IMapper mapper)
            {
            _settingsService = settingsService;
            _mapper = mapper;
        }

        /////////////--------------------------  C R U D ---------------------------------////////////////


        #region Item Group
        #region Get Method
        public IActionResult ItemGroup()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ItemGroupForm(int id = 0)
        {
            try
            {
                var viewModel = new ItemGroupVM();
                if (id > 0)
                {
                    viewModel = _settingsService.GetItemGroup(id);
                    if (viewModel == null) {
                        return Json(new { act = false, msg = "Data not found" });
                    }
                }
                ViewBag.Type = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(DropDownListUtility.GetCashTypeDropdown("Direct"), "Value", "Text", viewModel.Type);
                return PartialView("ItemGroupForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult ItemGroupList(String from, String to)
        {
            try
            {
                var viewModel = _settingsService.GetItemGroup();
                return PartialView("ItemGroupList", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion
        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveItemGroup(ItemGroupVM model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { act = false, msg = "Error! Invalid input" });
            }
            try
            {
                model.CreateDate = DateTime.UtcNow.AddHours(6);
                await _settingsService.SaveItemGroupAsync(model);

                var viewModel = _settingsService.GetItemGroup();
                return PartialView("ItemGroupList", viewModel);
            }
            catch (Exception ex)
            {
                return Json(new { act = false, msg = "Error! Data not saved" });
            }
        }


        [HttpPost]
        public async Task<JsonResult> ItemGroupDelete(int id)
        {
            try
            {
                await _settingsService.DeleteItemGroupAsync(id);
                return Json(new { act = true, msg = "Deleted! Changes saved successfully" });
            }
            catch (Exception ex)
            {
                //throw ex;
                return Json(new { act = false, msg = "Error! Error occured" });
            }
        }
        #endregion
        #endregion


        /////////////////////////////////////////////////////// ----------  Item  Name  -------------- ///////////////////////////////////////////////////////////////
        #region Item Name
        #region Get Method
        public IActionResult Item()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ItemForm(int id = 0)
        {
            try
            {
                var viewModel = new ItemVM();
                if (id > 0)
                {
                    viewModel = _settingsService.GetItem(id);
                    if (viewModel == null)
                    {
                        return Json(new { act = false, msg = "Data not found" });
                    }
                }
                SetItemViewBag("Item", viewModel);
                return PartialView("ItemForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult ItemList(String from, String to)
        {
            try
            {
                var viewModel = _settingsService.GetItem();
                return PartialView("ItemList", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion
        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveItem(ItemVM model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { act = false, msg = "Error! Invalid input" });
            }
            try
            {
                model.CreateDate = DateTime.UtcNow.AddHours(6);
                await _settingsService.SaveItemAsync(model);

                var viewModel = _settingsService.GetItem();
                return PartialView("ItemList", viewModel);
            }
            catch (Exception ex)
            {
                return Json(new { act = false, msg = "Error! Data not saved" });
            }
        }


        [HttpPost]
        public async Task<JsonResult> ItemDelete(int id)
        {
            try
            {
                await _settingsService.DeleteItemAsync(id);
                return Json(new { act = true, msg = "Deleted! Changes saved successfully" });
            }
            catch (Exception ex)
            {
                //throw ex;
                return Json(new { act = false, msg = "Error! Error occured" });
            }
        }
        #endregion
        #endregion

        /////////////////////////////////////////////////////// ----------  Company  -------------- ///////////////////////////////////////////////////////////////
        #region Company Name
        #region Get Method
        public IActionResult Company()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CompanyForm(int id = 0)
        {
            try
            {
                var viewModel = new CompanyVM();
                if (id > 0)
                {
                    viewModel = _settingsService.GetCompany(id);
                    if (viewModel == null)
                    {
                        return Json(new { act = false, msg = "Data not found" });
                    }
                }
                return PartialView("CompanyForm", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult CompanyList()
        {
            try
            {
                var viewModel = _settingsService.GetCompany();
                return PartialView("CompanyList", viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion
        #region Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveCompany(CompanyVM model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { act = false, msg = "Error! Invalid input" });
            }
            try
            {
                model.CreateDate = DateTime.UtcNow.AddHours(6);
                await _settingsService.SaveCompanyAsync(model);

                var viewModel = _settingsService.GetCompany();
                return PartialView("CompanyList", viewModel);
            }
            catch (Exception ex)
            {
                return Json(new { act = false, msg = "Error! Data not saved" });
            }
        }


        [HttpPost]
        public async Task<JsonResult> CompanyDelete(int id)
        {
            try
            {
                await _settingsService.DeleteCompanyAsync(id);
                return Json(new { act = true, msg = "Deleted! Changes saved successfully" });
            }
            catch (Exception ex)
            {
                //throw ex;
                return Json(new { act = false, msg = "Error! Error occured" });
            }
        }
        #endregion
        #endregion











        ////////////-----------------------------------------------/////////////////////

        #region Private method
        private void SetItemViewBag(string title, ItemVM model = null)
        {
            //TODO: UT
            try
            {
                ViewBag.IsModelValid = true;
                ViewBag.Title = title;
                if (model == null)
                {
                    ViewBag.GroupId = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_settingsService.GetItemGroup(), "Id", "GroupName");
                }
                else
                {
                    ViewBag.GroupId = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_settingsService.GetItemGroup(), "Id", "GroupName", model.GroupId);
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion
    }
}

AOTrade/AOTrade/Views/Settings/Company.cshtml
@{
    ViewData["Title"] = "ItemGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

        <div class="card-box" id="genericView">

            <input type="hidden" value="CompanyForm" id="formUrl">
            <input type="hidden" value="/Settings/CompanyDelete/" id="deleteUrl">

            <div class="form-sec">
                <form asp-controller="Settings" asp-action="SaveCompany" id="xformdata">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div id="formUI">

                    </div>
                </form>
            </div>

                <input type="hidden" value="CompanyList" id="datatableUrl">
                <div class="tbl-sec table-responsive" id="xdataList">
                    @*------------------Table Data------------------*@
                </div>
        </div>

AOTrade/AOTrade/Views/Settings/CompanyForm.cshtml
@model AOTrade.Models.ViewModel.CompanyVM

<input asp-for="Id" type="hidden" />
<div class="row">
    <div class="col-sm-12">
        <h4 class="m-t-0 m-b-30">Company Information</h4>
    </div>
</div>
<div class="row">

    <div class="col-sm-3">
        <span class="font-14 text-input-head">Company name</span>
        <input asp-for="CompanyName" class="form-control" required />
        <span asp-validation-for="CompanyName" class="text-danger"></span>
    </div>

    <div class="col-sm-6">
        <span class="font-14 text-input-head">Description</span>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="col-sm-2">
        <span class="font-14 text-input-head">Commission (%)</span>
        <input asp-for="CompanyPercent" class="form-control autonumber" placeholder="0.00" required />
        <span asp-validation-for="CompanyPercent" class="text-danger"></span>
    </div>

    <div class="col-sm-1">
        <span class="font-14 text-transparent">Save</span>
        <input class="btn btn-success save" value="Save" type="submit" style="width:100%" />
    </div>
</div>

AOTrade/AOTrade/Views/Settings/CompanyList.cshtml
@model IEnumerable<AOTrade.Models.ViewModel.CompanyVM>

<table class="data-table table table-bordered">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Company Name
            </th>
            <th>
                Description
            </th>
            <th>
                Commission
            </th>
            <th>
                Create Date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{ int sl = 0; }
        @foreach (var item in Model)
        {
            sl++;
        <tr>
            <td>
                @sl
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyPercent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td class="edit-delete">
                <a title="Edit" class="fa fa-edit fa-lg add-update" href="#" id="@item.Id"></a>&nbsp;
                @Html.Raw(" | ")&nbsp;<a title="Delete" class="text-danger fa fa-lg fa-trash-o delete" href="#" id="@item.Id"></a>
            </td>
        </tr>
        }
    </tbody>
</table>

AOTrade/AOTrade/Views/Settings/Item.cshtml
@{
    ViewData["Title"] = "ItemGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


        <div class="card-box" id="genericView">

            <input type="hidden" value="ItemForm" id="formUrl">
            <input type="hidden" value="/Settings/ItemDelete/" id="deleteUrl">

            <div class="form-sec">
                <form asp-controller="Settings" asp-action="SaveItem" id="xformdata">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div id="formUI">

                    </div>
                </form>
            </div>

                <input type="hidden" value="ItemList" id="datatableUrl">
                <div class="tbl-sec table-responsive" id="xdataList">
                    @*------------------Table Data------------------*@
                </div>
        </div>

AOTrade/AOTrade/Views/Settings/ItemForm.cshtml
@model AOTrade.Models.ViewModel.ItemVM

<input asp-for="Id" type="hidden" />

<div class="row">
    <div class="col-sm-12">
        <h4 class="m-t-0 m-b-30">Item Information</h4>
    </div>
</div>

<div class="row">
    <div class="col-sm-3">
        <span class="font-14 text-input-head">Item group</span>
        <select asp-for="GroupId" asp-items="ViewBag.GroupId" class="form-control select2" required>
            <option value="">--  Select group  --</option>        </select>
        <span asp-validation-for="GroupId" class="text-danger"></span>
    </div>

    <div class="col-sm-3">
        <span class="font-14 text-input-head">Item Name</span>
        <input asp-for="ItemName" class="form-control" required />
        <span asp-validation-for="ItemName" class="text-danger"></span>
    </div>
    <div class="col-sm-4">
        <span class="font-14 text-input-head">Description</span>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="col-sm-2">
        <span class="font-14 text-transparent">.</span>
        <input class="btn btn-success save" value="Save" type="submit" style="float:right;width:100%" />
    </div>
</div>

@*<td align="right">
    <button id="remove-form-row" type="button" class="btn btn-rounded btn-danger" style="display:none"> <i class="fa fa-remove"></i> </button>
    <button id="add-form-row" type="button" class="btn btn-rounded waves-effect waves-light btn-primary"> <i class="fa fa-plus"></i> </button>
</td>*@

AOTrade/AOTrade/Views/Settings/ItemGroup.cshtml
@{
    ViewData["Title"] = "ItemGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card-box" id="genericView">
            <input type="hidden" value="ItemGroupForm" id="formUrl">
            <input type="hidden" value="/Settings/ItemGroupDelete/" id="deleteUrl">

                <div class="form-sec">
                    <form asp-controller="Settings" asp-action="SaveItemGroup" id="xformdata">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div id="formUI">

                        </div>
                    </form>
                </div>


                <input type="hidden" value="ItemGroupList" id="datatableUrl">
                <div class="tbl-sec table-responsive" id="xdataList">
                    @*------------------Table Data------------------*@
                </div>
        </div>

AOTrade/AOTrade/Views/Settings/ItemGroupForm.cshtml
@model AOTrade.Models.ViewModel.ItemGroupVM

<input asp-for="Id" type="hidden" />

<div class="row">
    <div class="col-sm-12">
        <h4 class="m-t-0 m-b-30">Item Group</h4>
    </div>
</div>

<div class="row">
    <div class="col-sm-3">
        <span class="font-14 text-input-head">Group name</span>
        <input asp-for="GroupName" class="form-control" required />
        <span asp-validation-for="GroupName" class="text-danger"></span>
    </div>

    <div class="col-sm-5">
        <span class="font-14 text-input-head">Description</span>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="col-sm-2">
        <span class="font-14 text-input-head">Group type</span>
        <select asp-for="Type" asp-items="ViewBag.Type" class="form-control select2" required>
            <option value="">--  Select type  --</option>
        </select>
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>

    <div class="col-sm-2">
        <span class="font-14 text-transparent">Save</span>
        <input class="btn btn-success save" value="Save" type="submit" style="width:100%" />
    </div>
</div>

AOTrade/AOTrade/Views/Settings/ItemGroupList.cshtml
@model IEnumerable<AOTrade.Models.ViewModel.ItemGroupVM>

<table class="table table-bordered data-table">
    <thead>
        <tr>
            <th>
            #
            </th>
            <th>
                Group Name
            </th>
            <th>
                Description
            </th>
            <th>
                Group  type
            </th>
            <th>
                Create Date
            </th>
            <th></th>
        </tr>
    </thead>
    @{ int sl = 0; }
    @foreach (var item in Model)
    {
        sl++;
        <tr>
            <td>
                @sl
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GroupName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td class="edit-delete">
                <a title="Edit" class="fa fa-edit fa-lg add-update" href="#" id="@item.Id"></a>&nbsp;
                @Html.Raw(" | ")&nbsp;<a title="Delete" class="text-danger fa fa-lg fa-trash-o delete" href="#" id="@item.Id"></a>
            </td>
        </tr>
    }
    </tbody>
</table>

AOTrade/AOTrade/Views/Settings/ItemList.cshtml
@model IEnumerable<AOTrade.Models.ViewModel.ItemVM>

<table class="data-table table table-bordered">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Item group
            </th>
            <th>
                Item name
            </th>
            <th>
                Description
            </th>
            <th>
                Create date
            </th>
            <th></th>
        </tr>
    </thead>
    @{ int sl = 0; }
    @foreach (var item in Model)
    {
        sl++;
        <tr>
            <td>
                @sl
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group.GroupName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td class="edit-delete">
                <a title="Edit" class="fa fa-edit fa-lg add-update" href="#" id="@item.Id"></a>&nbsp;
                @Html.Raw(" | ")&nbsp;<a title="Delete" class="text-danger fa fa-lg fa-trash-o delete" href="#" id="@item.Id"></a>
            </td>
        </tr>
    }
    </tbody>
</table>